version: '2'

volumes:
  meetup-mysql-data:
    driver: local
  meetup-redis-data:
    driver: local

services:
  mysql:
    image: ambientum/mysql:5.7
    container_name: meetup-mysql
    volumes:
      - meetup-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=meetup
      - MYSQL_DATABASE=meetup
      - MYSQL_USER=meetup
      - MYSQL_PASSWORD=secret

  cache:
    image: ambientum/redis:3.2
    container_name: meetup-redis
    command: --appendonly yes
    volumes:
      - meetup-redis-data:/data
    ports:
      - "6379:6379"

  app:
    image: ambientum/php:7.0-apache
    container_name: meetup-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  queue:
    image: ambientum/php:7.0
    container_name: meetup-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache

  vue:
    image: ambientum/vue-cli
    container_name: meetup-vue
    volumes:
      - .:/var/www/app

  dev:
    image: ambientum/node:6
    container_name: sandbox-vue-dev
    command: npm run dev
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"

  production-server:
    image: nginx:stable-alpine
    container_name: sandbox-preview-server
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "9090:80"
